apiVersion: v1
data:
  application.properties: |-
    kie.flyway.enabled = true
    quarkus.log.category."org.apache.http".level=INFO
    quarkus.log.level=INFO
    quarkus.flyway.migrate-at-start=true
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: dynamic-course-select
    sonataflow.org/workflow-app: dynamic-course-select
  name: dynamic-course-select-props
  namespace: {{ .Release.Namespace }}

