apiVersion: v1
kind: Service
metadata:
  name: mytesthttpservice
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: mytesthttpserver
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}

