apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sonataflow-platform-data-index-route
spec:
  port:
    targetPort: h2c
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: sonataflow-platform-data-index-service