service:
  port: 80
  targetPort: 12345
server:
  image: quay.io/orchestrator/dynamic-course-demo-server:latest
postgresql:
  secretRef:
    name: rhdh-postgresql-svcbind-postgres
    userKey: username
    passwordKey: password
  serviceRef:
    name: rhdh-postgresql
    port: 5432
    databaseName: sonataflow