apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    app: basic
    app.kubernetes.io/component: serverless-workflow
    app.kubernetes.io/managed-by: sonataflow-operator
    app.kubernetes.io/name: basic
    sonataflow.org/workflow-app: basic
    sonataflow.org/workflow-namespace: ""
  name: basic-secrets
stringData:
  BACKSTAGE_NOTIFICATIONS_URL: https://backstage-backstage.rhdh-operator
  NOTIFICATIONS_BEARER_TOKEN: replaceme
