apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudevent-listener
  labels:
    app: cloudevent-listener
spec:
  selector:
    matchLabels:
      app: cloudevent-listener
  template:
    metadata:
      labels:
        app: cloudevent-listener
    spec:
      containers:
        - name: cloudevent-listener
          image: quay.io/orchestrator/cloudevent-listener:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cloudevent-listener-svc
spec:
  selector:
    app: cloudevent-listener
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080