apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-mytesthttpserver
  namespace: {{ .Release.Namespace }}
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault  # Or "Localhost" if you have a custom profile
  containers:
    - name: myhttpserver
      image: {{ .Values.server.image }}
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - "ALL"
  restartPolicy: Always
