apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: software-template-workflow
  title: A workflow that invokes software templates from Backstage
  description: A sample workflow to invoke software templates and check their progress

  tags:
    - orchestrator
spec:
  owner: red-hat-developer-hub-authors
  system: red-hat-developer-hub
  type: service

  # matches workflow's dataInputSchema
  parameters: 
    - $schema: http://json-schema.org/draft-07/schema#
      title: Workflow input parameters
      type: object
      properties:
        orgName:
          title: Organization Name
          type: string
          description: GitHub Organization Name
        repoName:
          title: Repository Name
          type: string
          description: GitHub Repository Name
        serviceName:
          title: Service Name
          type: string
          description: The Service Name
        owner:
          title: Owner
          type: string
          description: The owner of the component
          pattern: >-
            ^(user|group):[A-Za-z0-9]([-A-Za-z0-9]*[A-Za-z0-9])?/([A-Za-z0-9]([-A-Za-z0-9]*[A-Za-z0-9])?)$
          default: user:default/guest
      required:
        - orgName
        - repoName
        - serviceName
        - owner
    

  steps:
    - id: runWorkflow
      name: Run workflow
      action: orchestrator:workflow:run
      input:
        workflow_id: software-template-workflow # matches the workflow ID from sonataflow
        parameters: ${{ parameters }}

  output:
    links:
      - title: Open workflow run
        url: "${{ steps.runWorkflow.output.instanceUrl }}"
